{{- if and (not .Values.global.existingSecret) (or (not .Values.config.existingSecret) (not .Values.database.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentregistry.fullname" . }}
  labels:
    {{- include "agentregistry.labels" . | nindent 4 }}
  {{- $annotations := include "agentregistry.annotations" (dict "annotations" dict "context" $) }}
  {{- if $annotations }}
  annotations:
    {{- $annotations | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not (or .Values.global.existingSecret .Values.database.existingSecret) }}
  POSTGRES_PASSWORD: {{ .Values.database.password | toString | b64enc | quote }}
  {{- end }}
  {{- if not (or .Values.global.existingSecret .Values.config.existingSecret) }}
  AGENT_REGISTRY_JWT_PRIVATE_KEY: {{ .Values.config.jwtPrivateKey | toString | b64enc | quote }}
  {{- end }}
{{- end }}
