// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Agent = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: AgentSpec;
    status?: Status;
};

export type AgentPackage = {
    identifier: string;
    registryType: string;
    transport: TransportProto;
    version: string;
};

export type AgentRemote = {
    type: string;
    url?: string;
};

export type AgentSpec = {
    description?: string;
    framework?: string;
    image?: string;
    language?: string;
    mcpServers?: Array<ResourceRef>;
    modelName?: string;
    modelProvider?: string;
    packages?: Array<AgentPackage>;
    prompts?: Array<ResourceRef>;
    readme?: Readme;
    remotes?: Array<AgentRemote>;
    repository?: Repository;
    skills?: Array<ResourceRef>;
    telemetryEndpoint?: string;
    title?: string;
    websiteUrl?: string;
};

export type ApplyResult = {
    apiVersion?: string;
    error?: string;
    kind?: string;
    name: string;
    namespace?: string;
    status: string;
    version?: string;
};

export type ApplyResultsResponse = {
    results: Array<ApplyResult>;
};

export type Condition = {
    lastTransitionTime?: string;
    message?: string;
    reason?: string;
    status: string;
    type: string;
};

export type Deployment = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: DeploymentSpec;
    status?: Status;
};

export type DeploymentSpec = {
    desiredState?: string;
    env?: {
        [key: string]: string;
    };
    preferRemote?: boolean;
    providerConfig?: {
        [key: string]: unknown;
    };
    providerRef: ResourceRef;
    targetRef: ResourceRef;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail>;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type HealthBody = {
    /**
     * Platform mode
     */
    platform_mode?: 'docker' | 'kubernetes';
    /**
     * Health status
     */
    status: string;
};

export type ListOutputAgentBody = {
    items: Array<Agent>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type ListOutputDeploymentBody = {
    items: Array<Deployment>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type ListOutputMcpServerBody = {
    items: Array<McpServer>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type ListOutputPromptBody = {
    items: Array<Prompt>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type ListOutputProviderBody = {
    items: Array<Provider>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type ListOutputSkillBody = {
    items: Array<Skill>;
    nextCursor?: string;
    semanticScores?: Array<number>;
};

export type McpArgument = {
    choices?: Array<string>;
    default?: string;
    description?: string;
    format?: string;
    isRepeated?: boolean;
    isRequired?: boolean;
    isSecret?: boolean;
    name?: string;
    placeholder?: string;
    type: string;
    value?: string;
    valueHint?: string;
    variables?: {
        [key: string]: McpInputVariable;
    };
};

export type McpIcon = {
    mimeType?: string;
    sizes?: Array<string>;
    src: string;
    theme?: string;
};

export type McpInputVariable = {
    choices?: Array<string>;
    default?: string;
    description?: string;
    format?: string;
    isRequired?: boolean;
    isSecret?: boolean;
    placeholder?: string;
    value?: string;
};

export type McpKeyValueInput = {
    choices?: Array<string>;
    default?: string;
    description?: string;
    format?: string;
    isRequired?: boolean;
    isSecret?: boolean;
    name: string;
    placeholder?: string;
    value?: string;
    variables?: {
        [key: string]: McpInputVariable;
    };
};

export type McpPackage = {
    environmentVariables?: Array<McpKeyValueInput>;
    fileSha256?: string;
    identifier: string;
    packageArguments?: Array<McpArgument>;
    registryBaseUrl?: string;
    registryType: string;
    runtimeArguments?: Array<McpArgument>;
    runtimeHint?: string;
    transport: McpTransport;
    version?: string;
};

export type McpServer = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: McpServerSpec;
    status?: Status;
};

export type McpServerSpec = {
    description?: string;
    icons?: Array<McpIcon>;
    packages?: Array<McpPackage>;
    readme?: Readme;
    remotes?: Array<McpTransport>;
    repository?: Repository;
    title?: string;
    websiteUrl?: string;
};

export type McpTransport = {
    headers?: Array<McpKeyValueInput>;
    type: string;
    url?: string;
};

export type ObjectMeta = {
    annotations?: {
        [key: string]: string;
    };
    createdAt?: string;
    deletionTimestamp?: string;
    labels?: {
        [key: string]: string;
    };
    name: string;
    namespace?: string;
    updatedAt?: string;
    version?: string;
};

export type PingBody = {
    /**
     * Ping response
     */
    pong: boolean;
};

export type Prompt = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: PromptSpec;
    status?: Status;
};

export type PromptSpec = {
    content?: string;
    description?: string;
    readme?: Readme;
};

export type Provider = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: ProviderSpec;
    status?: Status;
};

export type ProviderSpec = {
    config?: {
        [key: string]: unknown;
    };
    platform: string;
};

export type Readme = {
    content?: string;
    contentType?: string;
    encoding?: string;
    source?: string;
};

export type Repository = {
    id?: string;
    source?: string;
    subfolder?: string;
    url?: string;
};

export type ResourceRef = {
    kind: string;
    name: string;
    namespace?: string;
    version?: string;
};

export type Skill = {
    apiVersion: string;
    kind: string;
    metadata: ObjectMeta;
    spec: SkillSpec;
    status?: Status;
};

export type SkillPackage = {
    identifier: string;
    registryType: string;
    transport: TransportProto;
    version: string;
};

export type SkillRemote = {
    url?: string;
};

export type SkillSpec = {
    category?: string;
    description?: string;
    packages?: Array<SkillPackage>;
    readme?: Readme;
    remotes?: Array<SkillRemote>;
    repository?: Repository;
    title?: string;
    websiteUrl?: string;
};

export type Status = {
    conditions?: Array<Condition>;
};

export type TransportProto = {
    type: string;
};

export type VersionBody = {
    /**
     * Build timestamp
     */
    build_time: string;
    /**
     * Git commit SHA
     */
    git_commit: string;
    /**
     * Application version
     */
    version: string;
};

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/agents';
};

export type ListAgentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors];

export type ListAgentsResponses = {
    /**
     * OK
     */
    200: ListOutputAgentBody;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetLatestAgentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}';
};

export type GetLatestAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestAgentError = GetLatestAgentErrors[keyof GetLatestAgentErrors];

export type GetLatestAgentResponses = {
    /**
     * OK
     */
    200: Agent;
};

export type GetLatestAgentResponse = GetLatestAgentResponses[keyof GetLatestAgentResponses];

export type DeleteAgentData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/agents/{name}/{version}';
};

export type DeleteAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors];

export type DeleteAgentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses];

export type GetAgentData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/{version}';
};

export type GetAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * OK
     */
    200: Agent;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type ApplyAgentData = {
    body?: Agent;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/{version}';
};

export type ApplyAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyAgentError = ApplyAgentErrors[keyof ApplyAgentErrors];

export type ApplyAgentResponses = {
    /**
     * OK
     */
    200: Agent;
};

export type ApplyAgentResponse = ApplyAgentResponses[keyof ApplyAgentResponses];

export type GetLatestAgentReadmeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/readme';
};

export type GetLatestAgentReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestAgentReadmeError = GetLatestAgentReadmeErrors[keyof GetLatestAgentReadmeErrors];

export type GetLatestAgentReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetLatestAgentReadmeResponse = GetLatestAgentReadmeResponses[keyof GetLatestAgentReadmeResponses];

export type GetAgentReadmeData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/agents/{name}/versions/{version}/readme';
};

export type GetAgentReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentReadmeError = GetAgentReadmeErrors[keyof GetAgentReadmeErrors];

export type GetAgentReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetAgentReadmeResponse = GetAgentReadmeResponses[keyof GetAgentReadmeResponses];

export type DeleteBatchData = {
    body: Blob | File;
    path?: never;
    query?: {
        /**
         * Run validation and enrichment without mutating the store. Defaults to false.
         */
        dryRun?: boolean;
    };
    url: '/v0/apply';
};

export type DeleteBatchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteBatchError = DeleteBatchErrors[keyof DeleteBatchErrors];

export type DeleteBatchResponses = {
    /**
     * OK
     */
    200: ApplyResultsResponse;
};

export type DeleteBatchResponse = DeleteBatchResponses[keyof DeleteBatchResponses];

export type ApplyBatchData = {
    body: Blob | File;
    path?: never;
    query?: {
        /**
         * Run validation and enrichment without mutating the store. Defaults to false.
         */
        dryRun?: boolean;
    };
    url: '/v0/apply';
};

export type ApplyBatchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyBatchError = ApplyBatchErrors[keyof ApplyBatchErrors];

export type ApplyBatchResponses = {
    /**
     * OK
     */
    200: ApplyResultsResponse;
};

export type ApplyBatchResponse = ApplyBatchResponses[keyof ApplyBatchResponses];

export type ListDeploymentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/deployments';
};

export type ListDeploymentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListDeploymentsError = ListDeploymentsErrors[keyof ListDeploymentsErrors];

export type ListDeploymentsResponses = {
    /**
     * OK
     */
    200: ListOutputDeploymentBody;
};

export type ListDeploymentsResponse = ListDeploymentsResponses[keyof ListDeploymentsResponses];

export type GetLatestDeploymentData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}';
};

export type GetLatestDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestDeploymentError = GetLatestDeploymentErrors[keyof GetLatestDeploymentErrors];

export type GetLatestDeploymentResponses = {
    /**
     * OK
     */
    200: Deployment;
};

export type GetLatestDeploymentResponse = GetLatestDeploymentResponses[keyof GetLatestDeploymentResponses];

export type DeleteDeploymentData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/deployments/{name}/{version}';
};

export type DeleteDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteDeploymentError = DeleteDeploymentErrors[keyof DeleteDeploymentErrors];

export type DeleteDeploymentResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteDeploymentResponse = DeleteDeploymentResponses[keyof DeleteDeploymentResponses];

export type GetDeploymentData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}/{version}';
};

export type GetDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetDeploymentError = GetDeploymentErrors[keyof GetDeploymentErrors];

export type GetDeploymentResponses = {
    /**
     * OK
     */
    200: Deployment;
};

export type GetDeploymentResponse = GetDeploymentResponses[keyof GetDeploymentResponses];

export type ApplyDeploymentData = {
    body?: Deployment;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/deployments/{name}/{version}';
};

export type ApplyDeploymentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyDeploymentError = ApplyDeploymentErrors[keyof ApplyDeploymentErrors];

export type ApplyDeploymentResponses = {
    /**
     * OK
     */
    200: Deployment;
};

export type ApplyDeploymentResponse = ApplyDeploymentResponses[keyof ApplyDeploymentResponses];

export type GetHealthV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/health';
};

export type GetHealthV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetHealthV0Error = GetHealthV0Errors[keyof GetHealthV0Errors];

export type GetHealthV0Responses = {
    /**
     * OK
     */
    200: HealthBody;
};

export type GetHealthV0Response = GetHealthV0Responses[keyof GetHealthV0Responses];

export type ListMcpserversData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/mcpservers';
};

export type ListMcpserversErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMcpserversError = ListMcpserversErrors[keyof ListMcpserversErrors];

export type ListMcpserversResponses = {
    /**
     * OK
     */
    200: ListOutputMcpServerBody;
};

export type ListMcpserversResponse = ListMcpserversResponses[keyof ListMcpserversResponses];

export type GetLatestMcpserverData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}';
};

export type GetLatestMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestMcpserverError = GetLatestMcpserverErrors[keyof GetLatestMcpserverErrors];

export type GetLatestMcpserverResponses = {
    /**
     * OK
     */
    200: McpServer;
};

export type GetLatestMcpserverResponse = GetLatestMcpserverResponses[keyof GetLatestMcpserverResponses];

export type DeleteMcpserverData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/mcpservers/{name}/{version}';
};

export type DeleteMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteMcpserverError = DeleteMcpserverErrors[keyof DeleteMcpserverErrors];

export type DeleteMcpserverResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteMcpserverResponse = DeleteMcpserverResponses[keyof DeleteMcpserverResponses];

export type GetMcpserverData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/{version}';
};

export type GetMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMcpserverError = GetMcpserverErrors[keyof GetMcpserverErrors];

export type GetMcpserverResponses = {
    /**
     * OK
     */
    200: McpServer;
};

export type GetMcpserverResponse = GetMcpserverResponses[keyof GetMcpserverResponses];

export type ApplyMcpserverData = {
    body?: McpServer;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/{version}';
};

export type ApplyMcpserverErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyMcpserverError = ApplyMcpserverErrors[keyof ApplyMcpserverErrors];

export type ApplyMcpserverResponses = {
    /**
     * OK
     */
    200: McpServer;
};

export type ApplyMcpserverResponse = ApplyMcpserverResponses[keyof ApplyMcpserverResponses];

export type GetLatestMcpserverReadmeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/readme';
};

export type GetLatestMcpserverReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestMcpserverReadmeError = GetLatestMcpserverReadmeErrors[keyof GetLatestMcpserverReadmeErrors];

export type GetLatestMcpserverReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetLatestMcpserverReadmeResponse = GetLatestMcpserverReadmeResponses[keyof GetLatestMcpserverReadmeResponses];

export type GetMcpserverReadmeData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/mcpservers/{name}/versions/{version}/readme';
};

export type GetMcpserverReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMcpserverReadmeError = GetMcpserverReadmeErrors[keyof GetMcpserverReadmeErrors];

export type GetMcpserverReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetMcpserverReadmeResponse = GetMcpserverReadmeResponses[keyof GetMcpserverReadmeResponses];

export type PingV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/ping';
};

export type PingV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PingV0Error = PingV0Errors[keyof PingV0Errors];

export type PingV0Responses = {
    /**
     * OK
     */
    200: PingBody;
};

export type PingV0Response = PingV0Responses[keyof PingV0Responses];

export type ListPromptsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/prompts';
};

export type ListPromptsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListPromptsError = ListPromptsErrors[keyof ListPromptsErrors];

export type ListPromptsResponses = {
    /**
     * OK
     */
    200: ListOutputPromptBody;
};

export type ListPromptsResponse = ListPromptsResponses[keyof ListPromptsResponses];

export type GetLatestPromptData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}';
};

export type GetLatestPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPromptError = GetLatestPromptErrors[keyof GetLatestPromptErrors];

export type GetLatestPromptResponses = {
    /**
     * OK
     */
    200: Prompt;
};

export type GetLatestPromptResponse = GetLatestPromptResponses[keyof GetLatestPromptResponses];

export type DeletePromptData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/prompts/{name}/{version}';
};

export type DeletePromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeletePromptError = DeletePromptErrors[keyof DeletePromptErrors];

export type DeletePromptResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeletePromptResponse = DeletePromptResponses[keyof DeletePromptResponses];

export type GetPromptData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/{version}';
};

export type GetPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPromptError = GetPromptErrors[keyof GetPromptErrors];

export type GetPromptResponses = {
    /**
     * OK
     */
    200: Prompt;
};

export type GetPromptResponse = GetPromptResponses[keyof GetPromptResponses];

export type ApplyPromptData = {
    body?: Prompt;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/{version}';
};

export type ApplyPromptErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyPromptError = ApplyPromptErrors[keyof ApplyPromptErrors];

export type ApplyPromptResponses = {
    /**
     * OK
     */
    200: Prompt;
};

export type ApplyPromptResponse = ApplyPromptResponses[keyof ApplyPromptResponses];

export type GetLatestPromptReadmeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/readme';
};

export type GetLatestPromptReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestPromptReadmeError = GetLatestPromptReadmeErrors[keyof GetLatestPromptReadmeErrors];

export type GetLatestPromptReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetLatestPromptReadmeResponse = GetLatestPromptReadmeResponses[keyof GetLatestPromptReadmeResponses];

export type GetPromptReadmeData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/prompts/{name}/versions/{version}/readme';
};

export type GetPromptReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetPromptReadmeError = GetPromptReadmeErrors[keyof GetPromptReadmeErrors];

export type GetPromptReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetPromptReadmeResponse = GetPromptReadmeResponses[keyof GetPromptReadmeResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/providers';
};

export type ListProvidersErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListProvidersError = ListProvidersErrors[keyof ListProvidersErrors];

export type ListProvidersResponses = {
    /**
     * OK
     */
    200: ListOutputProviderBody;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type GetLatestProviderData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/providers/{name}';
};

export type GetLatestProviderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestProviderError = GetLatestProviderErrors[keyof GetLatestProviderErrors];

export type GetLatestProviderResponses = {
    /**
     * OK
     */
    200: Provider;
};

export type GetLatestProviderResponse = GetLatestProviderResponses[keyof GetLatestProviderResponses];

export type DeleteProviderData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/providers/{name}/{version}';
};

export type DeleteProviderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteProviderError = DeleteProviderErrors[keyof DeleteProviderErrors];

export type DeleteProviderResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteProviderResponse = DeleteProviderResponses[keyof DeleteProviderResponses];

export type GetProviderData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/providers/{name}/{version}';
};

export type GetProviderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetProviderError = GetProviderErrors[keyof GetProviderErrors];

export type GetProviderResponses = {
    /**
     * OK
     */
    200: Provider;
};

export type GetProviderResponse = GetProviderResponses[keyof GetProviderResponses];

export type ApplyProviderData = {
    body?: Provider;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/providers/{name}/{version}';
};

export type ApplyProviderErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplyProviderError = ApplyProviderErrors[keyof ApplyProviderErrors];

export type ApplyProviderResponses = {
    /**
     * OK
     */
    200: Provider;
};

export type ApplyProviderResponse = ApplyProviderResponses[keyof ApplyProviderResponses];

export type ListSkillsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Namespace (defaults to 'default'; 'all' lists across all namespaces).
         */
        namespace?: string;
        /**
         * Max items to return (default 50).
         */
        limit?: number;
        /**
         * Opaque pagination cursor.
         */
        cursor?: string;
        /**
         * Label selector: key=value,key2=value2.
         */
        labels?: string;
        /**
         * Only return rows with is_latest_version=true.
         */
        latestOnly?: boolean;
        /**
         * Include rows with a deletionTimestamp.
         */
        includeTerminating?: boolean;
        /**
         * Semantic search query. Returns results ranked by similarity.
         */
        semantic?: string;
        /**
         * Drop results with cosine distance above this threshold (0 = no filter).
         */
        semanticThreshold?: number;
    };
    url: '/v0/skills';
};

export type ListSkillsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSkillsError = ListSkillsErrors[keyof ListSkillsErrors];

export type ListSkillsResponses = {
    /**
     * OK
     */
    200: ListOutputSkillBody;
};

export type ListSkillsResponse = ListSkillsResponses[keyof ListSkillsResponses];

export type GetLatestSkillData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}';
};

export type GetLatestSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestSkillError = GetLatestSkillErrors[keyof GetLatestSkillErrors];

export type GetLatestSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type GetLatestSkillResponse = GetLatestSkillResponses[keyof GetLatestSkillResponses];

export type DeleteSkillData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
        /**
         * Skip provider-specific teardown and only remove the registry record.
         */
        force?: boolean;
    };
    url: '/v0/skills/{name}/{version}';
};

export type DeleteSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type DeleteSkillError = DeleteSkillErrors[keyof DeleteSkillErrors];

export type DeleteSkillResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteSkillResponse = DeleteSkillResponses[keyof DeleteSkillResponses];

export type GetSkillData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/{version}';
};

export type GetSkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillError = GetSkillErrors[keyof GetSkillErrors];

export type GetSkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type GetSkillResponse = GetSkillResponses[keyof GetSkillResponses];

export type ApplySkillData = {
    body?: Skill;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/{version}';
};

export type ApplySkillErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ApplySkillError = ApplySkillErrors[keyof ApplySkillErrors];

export type ApplySkillResponses = {
    /**
     * OK
     */
    200: Skill;
};

export type ApplySkillResponse = ApplySkillResponses[keyof ApplySkillResponses];

export type GetLatestSkillReadmeData = {
    body?: never;
    path: {
        name: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/readme';
};

export type GetLatestSkillReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetLatestSkillReadmeError = GetLatestSkillReadmeErrors[keyof GetLatestSkillReadmeErrors];

export type GetLatestSkillReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetLatestSkillReadmeResponse = GetLatestSkillReadmeResponses[keyof GetLatestSkillReadmeResponses];

export type GetSkillReadmeData = {
    body?: never;
    path: {
        name: string;
        version: string;
    };
    query?: {
        /**
         * Namespace (internal; defaults to 'default').
         */
        namespace?: string;
    };
    url: '/v0/skills/{name}/versions/{version}/readme';
};

export type GetSkillReadmeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetSkillReadmeError = GetSkillReadmeErrors[keyof GetSkillReadmeErrors];

export type GetSkillReadmeResponses = {
    /**
     * OK
     */
    200: Readme;
};

export type GetSkillReadmeResponse = GetSkillReadmeResponses[keyof GetSkillReadmeResponses];

export type GetVersionV0Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v0/version';
};

export type GetVersionV0Errors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetVersionV0Error = GetVersionV0Errors[keyof GetVersionV0Errors];

export type GetVersionV0Responses = {
    /**
     * OK
     */
    200: VersionBody;
};

export type GetVersionV0Response = GetVersionV0Responses[keyof GetVersionV0Responses];
